#!/usr/bin/env bash
# Interactively create a per-world env file (.env.world-<id>) — the single
# source of truth consumed by docker-compose.world.yml (--env-file),
# render-assets.sh and multiworld-init-db.sh. Replaces copy-and-edit of
# .env.world-*.example.
#
#   ./new-world.sh              # prompts for the world id, then each field
#   ./new-world.sh c            # seeds defaults for world 'c'
#   ./new-world.sh --slot 3 c   # force login slot / account_id 3 (no slot prompt)
#   ./new-world.sh --no-haproxy c   # skip the HAProxy edits
#   ./new-world.sh --force c    # regenerate an already-configured world
#
# Idempotent: if .env.world-<id> already exists it does nothing (exit 0) unless
# --force is given.
#
# It then runs render-haproxy.sh, which regenerates haproxy/haproxy.cfg and
# haproxy/docker-compose.yml from ALL .env.world-* files, unless --no-haproxy is
# given. Those two outputs are generated and gitignored; only the .template files
# are tracked. Regenerating from every env file (rather than editing this world's
# block in place) is what keeps a `git pull` on the server from wiping the other
# worlds' registrations.
#
# Press Enter at any prompt to accept the [default]. Defaults for slot/ports are
# derived from the highest ACCOUNT_ID already in use, so worlds don't collide.
set -euo pipefail

cd "$(dirname "$0")"

ask() { # <var> <prompt> [default]
    local __var="$1" __prompt="$2" __def="${3:-}" __in
    if [ -n "$__def" ]; then
        read -r -p "$__prompt [$__def]: " __in || true
        printf -v "$__var" '%s' "${__in:-$__def}"
    else
        read -r -p "$__prompt: " __in || true
        printf -v "$__var" '%s' "$__in"
    fi
}

# next free login slot = 1 + max ACCOUNT_ID across existing world env files
next_slot() {
    local max=0 f v
    for f in .env.world-*; do
        [ -f "$f" ] || continue
        case "$f" in *.example) continue ;; esac
        v=$(grep -E '^ACCOUNT_ID=' "$f" 2>/dev/null | tail -1 | cut -d= -f2 | tr -dc '0-9')
        [ -n "$v" ] && [ "$v" -gt "$max" ] && max="$v"
    done
    echo $((max + 1))
}

DO_HAPROXY=1
SLOT=""
FORCE=0
while [ $# -gt 0 ]; do
    case "$1" in
        --no-haproxy) DO_HAPROXY=0; shift ;;
        --slot)       SLOT="${2:-}"; shift 2 ;;
        --slot=*)     SLOT="${1#*=}"; shift ;;
        --force)      FORCE=1; shift ;;
        --)           shift; break ;;
        -*)           echo "error: unknown option '$1'" >&2; exit 1 ;;
        *)            break ;;
    esac
done

WORLD="${1:-}"
[ -n "$WORLD" ] || ask WORLD "World id (short, e.g. a b c)"
WORLD=$(printf '%s' "$WORLD" | tr -dc 'a-zA-Z0-9')
[ -n "$WORLD" ] || { echo "error: world id required (letters/digits)" >&2; exit 1; }

ENV_FILE=".env.world-$WORLD"
if [ -e "$ENV_FILE" ] && [ "$FORCE" -ne 1 ]; then
    echo ">> $ENV_FILE already exists — nothing to do (pass --force to regenerate)."
    exit 0
fi

slot=$(next_slot); [ "$slot" -le 4 ] || slot=4
if [ -n "$SLOT" ]; then
    ACCOUNT_ID="$SLOT"          # given via --slot; skip the prompt
else
    ask ACCOUNT_ID "Login slot / account_id (0-4, unique per world)" "$slot"
fi
case "$ACCOUNT_ID" in ''|*[!0-9]*) echo "error: ACCOUNT_ID must be an integer 0-4" >&2; exit 1 ;; esac
{ [ "$ACCOUNT_ID" -ge 0 ] && [ "$ACCOUNT_ID" -le 4 ]; } \
    || { echo "error: ACCOUNT_ID must be 0-4 (source: #define MAX_SERVERS 5)" >&2; exit 1; }

upper=$(printf '%s' "$WORLD" | tr '[:lower:]' '[:upper:]')
ask WORLD_DB        "World database name"                     "world_$WORLD"
ask SERVER_USERID   "Interserver userid (sex='S' account)"    "s$ACCOUNT_ID"
ask SERVER_PASSWORD "Interserver password (change for prod!)" "p$ACCOUNT_ID"
ask SERVER_NAME     "Server name (world-select screen)"       "World$upper"
ask CHAR_PORT       "Char server port"                        "$((6111 + 10 * ACCOUNT_ID))"
ask MAP_PORT        "Map server port"                         "$((5111 + 10 * ACCOUNT_ID))"
ask PUBLIC_IP       "Public address advertised to clients"    "ro.example.com"

umask 077   # this file holds the interserver password
cat > "$ENV_FILE" <<EOF
# Generated by new-world.sh — single source of truth for world '$WORLD'.
# Consumed by docker-compose.world.yml (--env-file), render-assets.sh,
# and multiworld-init-db.sh. Re-run new-world.sh (overwrite) or edit by hand.
WORLD=$WORLD
CONFIG_DIR=./asset-world-$WORLD

# --- database + interserver account (multiworld-init-db.sh) ---
WORLD_DB=$WORLD_DB
# login slot: unique per world, integer 0-4 (source: #define MAX_SERVERS 5)
ACCOUNT_ID=$ACCOUNT_ID

# --- interserver login account + client-facing config (render-assets.sh) ---
SERVER_USERID=$SERVER_USERID
SERVER_PASSWORD=$SERVER_PASSWORD
SERVER_NAME=$SERVER_NAME
CHAR_PORT=$CHAR_PORT
MAP_PORT=$MAP_PORT
PUBLIC_IP=$PUBLIC_IP

# --- optional per-world gameplay knobs (render-assets.sh defaults them) ---
# Stat caps, rendered into battle_conf.txt. Default to stock if unset (99 / 99 /
# 80). Raise them alongside a raised level cap — at 99 the six stats are
# saturated by base level 181, so levels past that buy nothing.
# MAX_TRANS_PARAMETER defaults to MAX_PARAMETER: transcendent jobs are the
# pre-renewal endgame and have their OWN cap, so setting only max_parameter
# would leave Lord Knight, High Priest and friends at 99.
# See SETUP.md, "Per-world level cap".
#MAX_PARAMETER=99
#MAX_TRANS_PARAMETER=99
#MAX_BABY_PARAMETER=80
EOF

echo
echo ">> wrote $ENV_FILE"

# ---- HAProxy: regenerate from every world env file ----
# NOT an in-place upsert. haproxy.cfg / haproxy/docker-compose.yml are generated
# from the .env.world-* files and gitignored; only the .template files are
# tracked. See the comment at the top of render-haproxy.sh for why: the old
# accumulate-in-place approach made a git-tracked file hold runtime state, so a
# pull on the server wiped every previously registered world.
if [ "$DO_HAPROXY" -eq 1 ]; then
    ./render-haproxy.sh          # cwd is this script's dir (see cd at the top)
fi

echo "   next:"
echo "     ./render-assets.sh       --env-file $ENV_FILE"
echo "     ./multiworld-init-db.sh  --env-file $ENV_FILE   # after login stack is up"
echo "     docker compose -f docker-compose.world.yml --env-file $ENV_FILE up -d"
if [ "$DO_HAPROXY" -eq 1 ]; then
    echo "     docker compose -f haproxy/docker-compose.yml up -d   # apply new ports"
fi
