#!/usr/bin/env bash
# Interactively create a per-world env file (.env.world-<id>) — the single
# source of truth consumed by docker-compose.world.yml (--env-file),
# render-assets.sh and multiworld-init-db.sh. Replaces copy-and-edit of
# .env.world-*.example.
#
#   ./new-world.sh              # prompts for the world id, then each field
#   ./new-world.sh c            # seeds defaults for world 'c'
#   ./new-world.sh --slot 3 c   # force login slot / account_id 3 (no slot prompt)
#   ./new-world.sh --no-haproxy c   # skip the HAProxy edits
#   ./new-world.sh --force c    # regenerate an already-configured world
#
# Idempotent: if .env.world-<id> already exists it does nothing (exit 0) unless
# --force is given.
#
# It also upserts this world's HAProxy frontend/backend block into
# haproxy/haproxy.cfg and its published ports into haproxy/docker-compose.yml
# (idempotent, marker-delimited) unless --no-haproxy is given.
#
# Press Enter at any prompt to accept the [default]. Defaults for slot/ports are
# derived from the highest ACCOUNT_ID already in use, so worlds don't collide.
set -euo pipefail

cd "$(dirname "$0")"

ask() { # <var> <prompt> [default]
    local __var="$1" __prompt="$2" __def="${3:-}" __in
    if [ -n "$__def" ]; then
        read -r -p "$__prompt [$__def]: " __in || true
        printf -v "$__var" '%s' "${__in:-$__def}"
    else
        read -r -p "$__prompt: " __in || true
        printf -v "$__var" '%s' "$__in"
    fi
}

# next free login slot = 1 + max ACCOUNT_ID across existing world env files
next_slot() {
    local max=0 f v
    for f in .env.world-*; do
        [ -f "$f" ] || continue
        case "$f" in *.example) continue ;; esac
        v=$(grep -E '^ACCOUNT_ID=' "$f" 2>/dev/null | tail -1 | cut -d= -f2 | tr -dc '0-9')
        [ -n "$v" ] && [ "$v" -gt "$max" ] && max="$v"
    done
    echo $((max + 1))
}

DO_HAPROXY=1
SLOT=""
FORCE=0
while [ $# -gt 0 ]; do
    case "$1" in
        --no-haproxy) DO_HAPROXY=0; shift ;;
        --slot)       SLOT="${2:-}"; shift 2 ;;
        --slot=*)     SLOT="${1#*=}"; shift ;;
        --force)      FORCE=1; shift ;;
        --)           shift; break ;;
        -*)           echo "error: unknown option '$1'" >&2; exit 1 ;;
        *)            break ;;
    esac
done

WORLD="${1:-}"
[ -n "$WORLD" ] || ask WORLD "World id (short, e.g. a b c)"
WORLD=$(printf '%s' "$WORLD" | tr -dc 'a-zA-Z0-9')
[ -n "$WORLD" ] || { echo "error: world id required (letters/digits)" >&2; exit 1; }

ENV_FILE=".env.world-$WORLD"
if [ -e "$ENV_FILE" ] && [ "$FORCE" -ne 1 ]; then
    echo ">> $ENV_FILE already exists — nothing to do (pass --force to regenerate)."
    exit 0
fi

slot=$(next_slot); [ "$slot" -le 4 ] || slot=4
if [ -n "$SLOT" ]; then
    ACCOUNT_ID="$SLOT"          # given via --slot; skip the prompt
else
    ask ACCOUNT_ID "Login slot / account_id (0-4, unique per world)" "$slot"
fi
case "$ACCOUNT_ID" in ''|*[!0-9]*) echo "error: ACCOUNT_ID must be an integer 0-4" >&2; exit 1 ;; esac
{ [ "$ACCOUNT_ID" -ge 0 ] && [ "$ACCOUNT_ID" -le 4 ]; } \
    || { echo "error: ACCOUNT_ID must be 0-4 (source: #define MAX_SERVERS 5)" >&2; exit 1; }

upper=$(printf '%s' "$WORLD" | tr '[:lower:]' '[:upper:]')
ask WORLD_DB        "World database name"                     "world_$WORLD"
ask SERVER_USERID   "Interserver userid (sex='S' account)"    "s$ACCOUNT_ID"
ask SERVER_PASSWORD "Interserver password (change for prod!)" "p$ACCOUNT_ID"
ask SERVER_NAME     "Server name (world-select screen)"       "World$upper"
ask CHAR_PORT       "Char server port"                        "$((6111 + 10 * ACCOUNT_ID))"
ask MAP_PORT        "Map server port"                         "$((5111 + 10 * ACCOUNT_ID))"
ask PUBLIC_IP       "Public address advertised to clients"    "ro.example.com"

umask 077   # this file holds the interserver password
cat > "$ENV_FILE" <<EOF
# Generated by new-world.sh — single source of truth for world '$WORLD'.
# Consumed by docker-compose.world.yml (--env-file), render-assets.sh,
# and multiworld-init-db.sh. Re-run new-world.sh (overwrite) or edit by hand.
WORLD=$WORLD
CONFIG_DIR=./asset-world-$WORLD

# --- database + interserver account (multiworld-init-db.sh) ---
WORLD_DB=$WORLD_DB
# login slot: unique per world, integer 0-4 (source: #define MAX_SERVERS 5)
ACCOUNT_ID=$ACCOUNT_ID

# --- interserver login account + client-facing config (render-assets.sh) ---
SERVER_USERID=$SERVER_USERID
SERVER_PASSWORD=$SERVER_PASSWORD
SERVER_NAME=$SERVER_NAME
CHAR_PORT=$CHAR_PORT
MAP_PORT=$MAP_PORT
PUBLIC_IP=$PUBLIC_IP

# --- optional per-world gameplay knobs (render-assets.sh defaults them) ---
# Stat caps, rendered into battle_conf.txt. Default to stock if unset (99 / 99 /
# 80). Raise them alongside a raised level cap — at 99 the six stats are
# saturated by base level 181, so levels past that buy nothing.
# MAX_TRANS_PARAMETER defaults to MAX_PARAMETER: transcendent jobs are the
# pre-renewal endgame and have their OWN cap, so setting only max_parameter
# would leave Lord Knight, High Priest and friends at 99.
# See SETUP.md, "Per-world level cap".
#MAX_PARAMETER=99
#MAX_TRANS_PARAMETER=99
#MAX_BABY_PARAMETER=80
EOF

echo
echo ">> wrote $ENV_FILE"

# ---- HAProxy: upsert this world's frontend/backend block + published ports ----
CFG="haproxy/haproxy.cfg"
COMPOSE="haproxy/docker-compose.yml"

upsert_haproxy_cfg() {
    [ -f "$CFG" ] || { echo "   haproxy.cfg: not found — skipped"; return; }
    local start="# >>> world $WORLD (managed by new-world.sh)"
    local end="# <<< world $WORLD"
    local block
    printf -v block '%s\n' \
        "$start" \
        "frontend ${WORLD}_char" \
        "    bind :$CHAR_PORT" \
        "    tcp-request connection track-sc0 src table st_flood" \
        "    tcp-request connection reject if { sc0_conn_cur gt 50 }" \
        "    tcp-request connection reject if { sc0_conn_rate gt 100 }" \
        "    default_backend ${WORLD}_char_bk" \
        "frontend ${WORLD}_map" \
        "    bind :$MAP_PORT" \
        "    tcp-request connection track-sc0 src table st_flood" \
        "    tcp-request connection reject if { sc0_conn_cur gt 50 }" \
        "    tcp-request connection reject if { sc0_conn_rate gt 100 }" \
        "    default_backend ${WORLD}_map_bk" \
        "backend ${WORLD}_char_bk" \
        "    server char rathena-world-${WORLD}-char:$CHAR_PORT check resolvers docker init-addr last,libc,none" \
        "backend ${WORLD}_map_bk" \
        "    server map rathena-world-${WORLD}-map:$MAP_PORT check resolvers docker init-addr last,libc,none" \
        "$end"
    if grep -qxF "$start" "$CFG"; then
        awk -v s="$start" -v e="$end" -v blk="$block" '
            $0==s { printf "%s", blk; skip=1; next }
            skip  { if ($0==e) skip=0; next }
                  { print }
        ' "$CFG" > "$CFG.tmp" && mv "$CFG.tmp" "$CFG"
        echo "   haproxy.cfg: updated world $WORLD block ($CHAR_PORT/$MAP_PORT)"
    else
        printf '\n%s' "$block" >> "$CFG"
        echo "   haproxy.cfg: added world $WORLD block ($CHAR_PORT/$MAP_PORT)"
    fi
}

upsert_haproxy_ports() {
    [ -f "$COMPOSE" ] || { echo "   haproxy compose: not found — skipped"; return; }
    grep -q '# >>> world-ports' "$COMPOSE" \
        || { echo "   haproxy compose: no 'world-ports' region — skipped"; return; }
    local ind="            "                 # 12 spaces, matches the ports list
    local lc="${ind}- \"$CHAR_PORT:$CHAR_PORT\"   # world $WORLD"
    local lm="${ind}- \"$MAP_PORT:$MAP_PORT\"   # world $WORLD"
    awk -v lc="$lc" -v lm="$lm" -v tag="# world $WORLD" '
        /# >>> world-ports/            { print; inreg=1; next }
        inreg && /# <<< world-ports/   { print lc; print lm; print; inreg=0; next }
        inreg                          { if ($0 ~ (tag "$")) next; print; next }
                                       { print }
    ' "$COMPOSE" > "$COMPOSE.tmp" && mv "$COMPOSE.tmp" "$COMPOSE"
    echo "   haproxy compose: published ports $CHAR_PORT/$MAP_PORT for world $WORLD"
}

if [ "$DO_HAPROXY" -eq 1 ]; then
    upsert_haproxy_cfg
    upsert_haproxy_ports
fi

echo "   next:"
echo "     ./render-assets.sh       --env-file $ENV_FILE"
echo "     ./multiworld-init-db.sh  --env-file $ENV_FILE   # after login stack is up"
echo "     docker compose -f docker-compose.world.yml --env-file $ENV_FILE up -d"
if [ "$DO_HAPROXY" -eq 1 ]; then
    echo "     docker compose -f haproxy/docker-compose.yml up -d   # apply new ports"
fi
